name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-format-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Format code
        run: npm run format-check

      - name: Run tests
        run: npm test
      
      - name: Check for mismatched dependencies
        uses: davidanson/duplicate-package-checker-action@v5
        with:
          fail-on-mismatch: false

  ai-code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: your-username/ai-code-reviewer@main
        with:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          open_ai_model: gpt-3.5-turbo
          exclude: "**/*.json, **/*.md" 
          with-comment: true